### ISSUE TITLE
Upgrade is-url-superb to 4.0.0 to fix a bug

### ISSUE THREAD

**Issue by jaddison** [posthtml/posthtml-url-parameters#2]
## Problem

Described [here in the Maizzle project](https://github.com/maizzle/framework/issues/213); template variables in a URL break Maizzle's `urlParameters` functionality.

## Environment

- `posthtml-url-parameters` plugin version: 1.0.2
- PostHTML version: 0.13.0
- Node.js version: 13.8.0

## The Test + Fix
**Looks like the fix is to upgrade `is-url-superb` from 3.0.0 to 4.0.0**; this code returns `false` with 3.0.0, but `true` with 4.0.0 (I used repl.it):
```
require('is-url-superb')('https://example.com/{{ var }}')
```

**Comment by cossssmin** [comment]
Reopening this as it has not been actually solved, see failing test in https://github.com/posthtml/posthtml-url-parameters/commit/4c6994b9f8aea0ec57572c23a3ed8f1d67db65d7
